EmployeeManagement/Controllers/ImagecropController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileProviders;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;

namespace EmployeeManagement.Controllers
{
    public class ImagecropController : Controller
    {
        public IActionResult CustomCrop()
        {
            return View();
        }

        //this method is called after the Create action method in HomeController
        [HttpPost]
        public IActionResult CustomCrop(int employeeId, string uniqueFilename, IFormFile blob)
        {
            try
            {
                using (var image = Image.Load(blob.OpenReadStream()))
                {

                    var filepath = new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(), 
                        "wwwroot", "images")).Root + $@"\{uniqueFilename}";
                    image.Mutate(x => x.Resize(250, 250));
                    image.Save(filepath);

                }

                return RedirectToAction("details", new { id = employeeId });
            }
            catch (Exception)
            {
                return View("create");
            }
        }

        //[HttpPost]
        //public IActionResult CustomCrop(string filename, IFormFile blob)
        //{
        //    string PhotoName;
        //    try
        //    {
        //        using (var image = Image.Load(blob.OpenReadStream()))
        //        {
        //            string systemFileExtenstion = filename.Substring(filename.LastIndexOf('.'));

        //            string newfileName200 = GenerateFileName("Photo_200_200_", systemFileExtenstion);
        //            var filepath200 = new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images")).Root + $@"\{newfileName200}";
        //            image.Mutate(x => x.Resize(200, 200));
        //            image.Save(filepath200);

        //            string newfileName32 = GenerateFileName("Photo_32_32_", systemFileExtenstion);
        //            var filepath32 = new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images")).Root + $@"\{newfileName32}";
        //            image.Mutate(x => x.Resize(32, 32));
        //            image.Save(filepath32);

        //            PhotoName = newfileName200;
        //        }

        //        return Json(new { Message = "OK", FileName = PhotoName });
        //    }
        //    catch (Exception)
        //    {
        //        return Json(new { Message = "ERROR" });
        //    }
        //}

        public string GenerateFileName(string fileTypeName, string fileextenstion)
        {
            if (fileTypeName == null) throw new ArgumentNullException(nameof(fileTypeName));
            if (fileextenstion == null) throw new ArgumentNullException(nameof(fileextenstion));
            return $"{fileTypeName}_{DateTime.Now:yyyyMMddHHmmssfff}_{Guid.NewGuid():N}{fileextenstion}";
        }
    }
}

EmployeeManagement/Views/Shared/CustomCrop.cshtml
@{
    ViewBag.Title = "Crop Image";
}


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/croppie/2.6.5/croppie.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/croppie/2.6.5/croppie.min.js"></script>
<style>
    .croppie-container {
        width: 100%;
        height: 80%;
    }
</style>

<body>
    <div class="container">
        <div class="d-flex justify-content-center">
            <div class="col-md-6">

                <div class="card" style="margin-top:10px;">
                    <div class="card-header">Cropper in ASP.NET Core</div>
                    <div class="card-body">
                        <div id="main-cropper"></div>
                        <input type="file" id="select" class="form-control" value="Choose Image" accept="image/*">
                        <button id="btnupload" style="margin-top: 10px;" name="btnupload" class="btn btn-success">Crop</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">

        //initialize Croppie
        var basic = $('#main-cropper').croppie
            ({
                viewport: { width: 300, height: 300 },
                boundary: { width: 400, height: 400 },
                showZoomer: true,
                url: '/images/noimage.png',
                format: 'png' //'jpeg'|'png'|'webp'
            });

        //Reading the contents of the specified Blob or File
        function readFile(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#main-cropper').croppie('bind', {
                        url: e.target.result
                    });
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        // Change Event to Read file content from File input
        $('#select').on('change', function () { readFile(this); });

        // Upload button to Post Cropped Image to Store.
    $('#btnupload').on('click', function ()
    {
        basic.croppie('result', 'blob').then(function (blob)
        {
            var formData = new FormData();

            formData.append('filename', 'FileName.png');
            formData.append('blob', blob);
            var myAppUrlSettings =
            {
                MyUsefulUrl: '@Url.Action("CustomCrop", "Imagecrop")'
            }
            var request = new XMLHttpRequest();
            request.open('POST', myAppUrlSettings.MyUsefulUrl);
            request.send(formData);
            request.onreadystatechange = function () {
               // Call a function when the state changes.
                if (this.readyState === XMLHttpRequest.DONE && this.status === 200)
                {
                    var response = JSON.parse(request.responseText);

                    if (response.message == "OK")
                    {
                        alert('Photo Cropped Successfully!');
                        window.location.reload();
                    }
                    if (response.message == "ERROR")
                    {
                        alert('Photo Crop Unsuccessful!');
                        window.location.reload();
                    }
                }
            }
        });
    });

    </script>

</body>

EmployeeManagement/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "Not Found";
}

<h1>@ViewBag.ErrorMessage</h1>

<a asp-action="index" asp-controller="home">
    Click here to navigate to the home page
</a>

EmployeeManagement/Views/Shared/_Layout.cshtml
@inject  SignInManager<ApplicationUser> signInManager;


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <environment include="Development">
        <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/lib/jquery-validate/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.js"></script>

        <!-- Begin Cropper requirements -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/croppie/2.6.5/croppie.min.css" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/croppie/2.6.5/croppie.min.js"></script>
        <style>
            .croppie-container {
                width: 100%;
                height: 80%;
                margin: 5px;
            }
        </style>
        <!-- End -->

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
              integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l"
              crossorigin="anonymous"
              asp-fallback-href="~/lib/bootstrap/css/bootstrap.css"
              asp-fallback-test-class="sr-only"
              asp-fallback-test-property="position"
              asp-fallback-test-value="absolute"
              asp-suppress-fallback-integrity="true">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"
                integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
                crossorigin="anonymous"></script>
    </environment>
    <link href="~/css/site.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <a class="navbar-brand" asp-controller="home" asp-action="index">
                <img src="~/images/employees.png"  width="30" height="30" />
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a asp-controller="home" asp-action="index" class="nav-link">List</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="home" asp-action="create" class="nav-link">Create</a>
                    </li>
                    
                </ul>
                <ul class="navbar-nav ml-auto">
                    @if (signInManager.IsSignedIn(User))
                    {
                        <li class="nav-item">
                            <form method="post" asp-action="logout" asp-controller="account">
                                <button type="submit" class="nav-link btn btn-link py-0"
                                        style="width:auto">
                                    Logout @User.Identity.Name
                                </button>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a asp-controller="account" asp-action="register" class="nav-link">Register</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="account" asp-action="login" class="nav-link">Login</a>
                        </li>
                    }
                </ul>
            </div>
        </nav>
        <div>
            @RenderBody()
        </div>
    </div>
    @RenderSection("Scripts", required: false)
</body>
</html>